# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=100, verbose_name='Название')),
                ('album_slug', models.SlugField(max_length=100, unique=True, verbose_name='Описание')),
            ],
            options={
                'ordering': ['album_title'],
                'verbose_name_plural': 'Альбомы',
                'verbose_name': 'Альбом',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(upload_to='images', verbose_name='Photo')),
                ('photo_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album', verbose_name='Альбом')),
            ],
            options={
                'ordering': ['photo_title'],
                'verbose_name_plural': 'Фотографии',
                'verbose_name': 'Фото',
            },
        ),
    ]
