# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_title',
            new_name='title',
        ),
    ]
