# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCarouselPicture',
            fields=[
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('priority', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Приоритет в карусели')),
                ('image', models.ImageField(upload_to='head/', verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Картинка карусели',
                'verbose_name_plural': 'Картинки карусели',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
        migrations.DeleteModel(
            name='HeadPicture',
        ),
        migrations.DeleteModel(
            name='OurTeam',
        ),
    ]
