# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
