# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
