# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20161112_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=32),
        ),
    ]
