# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20161127_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
    ]
