# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20161127_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['timestamp'], 'verbose_name': 'Обратная связь'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='Ответ послан'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=32, verbose_name='Тема'),
        ),
    ]
