# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 13:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20161127_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='Отвечено'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MaxLengthValidator(32)], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тема'),
        ),
    ]
