# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('party_fullname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('party_email', models.CharField(max_length=200, verbose_name='Элекронная почта')),
                ('party_password', models.CharField(default=' ', max_length=200, verbose_name='Пароль')),
                ('party_phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('party_entry', models.NullBooleanField(default=False)),
                ('party_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
