# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 03:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('party_fullname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('party_email', models.CharField(max_length=200, verbose_name='Элекронная почта')),
                ('party_password', models.CharField(default=' ', max_length=200, verbose_name='Пароль')),
                ('party_phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('party_entry', models.NullBooleanField(default=False)),
                ('party_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default=None, max_length=200, verbose_name='Название курса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User profile',
            },
        ),
        migrations.CreateModel(
            name='UserRegisterConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(default=datetime.date(2016, 12, 11))),
            ],
        ),
    ]
