# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='party_out',
            new_name='party_entry',
        ),
        migrations.AlterField(
            model_name='party',
            name='party_phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
    ]
