# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20161225_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterconfirm',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 1, 9)),
        ),
    ]
