# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name_course', models.CharField(max_length=200, verbose_name='Название')),
                ('courses_date_begin', models.DateField(verbose_name='Дата начала')),
                ('courses_date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'ordering': ['courses_name_course'],
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
