# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name_course', models.CharField(max_length=200, verbose_name='Название')),
                ('courses_date_begin', models.DateField(verbose_name='Дата начала')),
                ('courses_date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'ordering': ['courses_name_course'],
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('party_fullname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('party_email', models.CharField(max_length=200, verbose_name='Элекронная почта')),
                ('party_login', models.CharField(default=' ', max_length=200, verbose_name='Логин')),
                ('party_password', models.CharField(default=' ', max_length=200, verbose_name='Пароль')),
                ('party_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
