# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170109_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_name'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_name_course',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_date_begin',
            new_name='date_begin',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courses_date_end',
            new_name='date_end',
        ),
    ]
